#!/usr/bin/env node

var request = require('request');
var nconf = require('nconf');
nconf.argv();
nconf.env();
nconf.file({ file: 'conf/'+nconf.get('NODE_ENV')+'.json' });

var index = require(nconf.get('base')+'/mod/index');
var category = require(nconf.get('base')+'/lib/category');

request(nconf.get('index:source'), function (error, response, data) {
  if (!error) {
    // cached
    index.get_json(data);
    console.log('Successfully get JSON');
  } else {
  	console.log('Getting JSON error');
  	console.log(error);
  }

});
request(nconf.get('category:source'), function (error, response, data) {
  if (!error) {
    category.request_json();
    console.log('Successfully request JSON');
  } else {
  	console.log('Request JSON error');
  	console.log(error);
  }

});
