#!/usr/bin/env node

var index = require('../lib/index');
var request = require('request');

request(index.spreadsheet_uri, function (error, response, data) {
  if (!error) {
    // cached
    index.get_json(data);
  }
});
